app: /app/{{ cookiecutter.app_folder_name }}
data-dir: /anvil_data
uplink-key: server_uplink_key
client-uplink-key: client_uplink_key
auto-migrate: true
port: "3030"  # Internal Docker port - do not change this
disable-tls: false  # Set to true when using Cloudflare Tunnel
smtp-host: smtp_host
smtp-port: 587
smtp-encryption: starttls
smtp-username: smtp_username
smtp-password: smtp_password